### ISSUE TITLE
Cannot convert float NaN to integer failure

### ISSUE THREAD

**Issue by lamping7** [dronecrew/ulog_tools#4]
Not sure what is going on here yet...

```
$ ulog_tools_pid_design --url https://review.px4.io/download?log=477be5e0-4491-442d-a0f6-f7ed1433c83c out.gains

Traceback (most recent call last):
  File "/home/tony/.local/bin/ulog_tools_pid_design", line 11, in <module>
    sys.exit(main())
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/control_opt.py", line 72, in main
    res = ut.sysid.attitude_sysid(data, plot=args.plot, verbose=args.verbose)
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/_sysid.py", line 223, in attitude_sysid
    y=series_diff(bandpass.apply(data['f_gyro_rad_0'])),
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/_sysid.py", line 74, in apply
    ftype=self.ftype)
  File "/home/tony/.local/lib/python3.5/site-packages/scipy/signal/filter_design.py", line 1819, in iirdesign
    N, Wn = ordfunc(wp, ws, gpass, gstop, analog=analog)
  File "/home/tony/.local/lib/python3.5/site-packages/scipy/signal/filter_design.py", line 3409, in ellipord
    ord = int(ceil(d0[0] * d1[1] / (d0[1] * d1[0])))
ValueError: cannot convert float NaN to integer
```

**Comment by lamping7** [comment]
Did some debugging and found that special.ellipk is returning nan because the result is a complex number (result: `[        nan  1.13599231]`, which was verified when plugging the numbers into Wolfram Alpha. https://www.wolframalpha.com/input/?i=EllipticK(%5B3.3408127571394615,+-2.3408127571394615%5D)

Looks like this goes way back --> https://github.com/scipy/scipy/issues/1431

I'm not sure if there is anything wrong with my data that is causing a complex result. Let me know if you've seen this before.

**Comment by lamping7** [comment]
I changed the PX4 SDLOG parameter to system identification, which I guess increased the logging rate and solved the issue.
