### ISSUE TITLE
Optimization failed

### ISSUE THREAD

**Issue by neom89** [dronecrew/ulog_tools#5]
I ran the ulog_tools_pid_design with a ulog file that has actuator_control and sensors_combined data collected at a sampling frequency of approximately 250 Hz. I got an error of optimization fail. Can you tell me what could be the probable cause of that?

Here is the log from the terminal:

cost 5.673527762080279
jac [-323803.75913374   13789.75133204 -101751.59051904]
constraint [4.83505592e-04 4.83505592e-04 2.16622455e+01 2.16622455e+01]
Traceback (most recent call last):
  File "/usr/local/bin/ulog_tools_pid_design", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ulog_tools/control_opt.py", line 90, in main
    est_delay=est_delay
  File "/usr/local/lib/python3.6/site-packages/ulog_tools/control_opt.py", line 29, in attitude_loop_design
    G=G_rate_ol, K_guess=[0.2, 0.2, 0], dcut_hz=dcut_hz)
  File "/usr/local/lib/python3.6/site-packages/ulog_tools/_lqrofb.py", line 157, in pid_design
    K = lqr_ofb_design(K_guess, ss_open, verbose)
  File "/usr/local/lib/python3.6/site-packages/ulog_tools/_lqrofb.py", line 116, in lqr_ofb_design
    raise RuntimeError('optimization failed')
RuntimeError: optimization failed

**Comment by jgoppert** [comment]
Closing as stale.
