### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'data'

### ISSUE THREAD

**Issue by cimbar** [dronecrew/ulog_tools#6]
Hi,
I have been using this tool before and it saves a lot of time on pid tuning. After a long time, i couldn't make this tool functional. When i used sample command line written on the readme file, i got this error and couldn't figure it out.

```
preparing data...
data prepared
identifying attitude dynamics...
Traceback (most recent call last):
  File "/usr/local/bin/ulog_tools_pid_design", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ulog_tools/control_opt.py", line 73, in main
    res = ut.sysid.attitude_sysid(data, plot=args.plot, verbose=args.verbose)
  File "/usr/local/lib/python3.6/dist-packages/ulog_tools/_sysid.py", line 223, in attitude_sysid
    y=series_diff(bandpass.apply(data['f_gyro_rad_0'])),
  File "/usr/local/lib/python3.6/dist-packages/ulog_tools/_sysid.py", line 42, in series_diff
    dx = np.gradient(series.data, order)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'data'
```

**Comment by cimbar** [comment]
I faced with this issue when i used pip3 install command. There is no problem installation from source using setup.py
